# Generated by Django 4.2.30 on 2026-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenomicTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "track_type",
                    models.CharField(
                        choices=[
                            ("alignment", "Alignment"),
                            ("variant", "Variant"),
                            ("annotation", "Annotation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("genome", models.CharField(default="hg38", max_length=20)),
                (
                    "url",
                    models.URLField(help_text="BAM/CRAM/VCF 文件 URL", max_length=500),
                ),
                (
                    "index_url",
                    models.URLField(help_text="BAI/CRAI/TBI 索引 URL", max_length=500),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("bam", "BAM"),
                            ("cram", "CRAM"),
                            ("vcf", "VCF"),
                            ("bed", "BED"),
                            ("bigwig", "BigWig"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
