# Generated by Django 4.2.30 on 2026-09-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_patient_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='patient_no',
        ),
    ]
