# Generated by Django 4.2.30 on 2026-09-02 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_data_v2_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('key_prefix', models.CharField(db_index=True, max_length=32)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('scope', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_api_keys_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '导入 API Key',
                'verbose_name_plural': '导入 API Key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('request_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, max_length=32)),
                ('error_detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ingest.ingestapikey')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_events', to='reports.report')),
            ],
            options={
                'verbose_name': '导入事件',
                'verbose_name_plural': '导入事件',
                'ordering': ['-created_at'],
            },
        ),
    ]
