# Generated by Django 4.2.30 on 2026-06-30 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="报告标题")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("methylation", "甲基化"),
                            ("mutation", "突变"),
                            ("msi", "MSI"),
                            ("cnv", "CNV"),
                        ],
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                ("sample_id", models.CharField(max_length=100, verbose_name="样本编号")),
                ("report_date", models.DateField(verbose_name="报告日期")),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                ("conclusion", models.TextField(blank=True, verbose_name="结论")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "检测报告",
                "verbose_name_plural": "检测报告",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="ReportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gene", models.CharField(max_length=50, verbose_name="基因名")),
                ("chromosome", models.CharField(max_length=10, verbose_name="染色体")),
                ("position", models.IntegerField(verbose_name="位置")),
                (
                    "end_position",
                    models.IntegerField(blank=True, null=True, verbose_name="终止位置"),
                ),
                (
                    "ref_allele",
                    models.CharField(blank=True, max_length=500, verbose_name="参考等位基因"),
                ),
                (
                    "alt_allele",
                    models.CharField(blank=True, max_length=500, verbose_name="变异等位基因"),
                ),
                (
                    "variant_type",
                    models.CharField(
                        choices=[
                            ("SNP", "SNP"),
                            ("InDel", "InDel"),
                            ("Methylation", "甲基化"),
                            ("Amplification", "扩增"),
                            ("Deletion", "缺失"),
                        ],
                        max_length=50,
                        verbose_name="变异类型",
                    ),
                ),
                (
                    "significance",
                    models.CharField(
                        choices=[
                            ("pathogenic", "致病性"),
                            ("likely_pathogenic", "可能致病"),
                            ("vus", "意义未明"),
                            ("likely_benign", "可能良性"),
                            ("benign", "良性"),
                        ],
                        default="vus",
                        max_length=50,
                        verbose_name="临床意义",
                    ),
                ),
                ("af", models.FloatField(blank=True, null=True, verbose_name="等位基因频率")),
                (
                    "methylation_level",
                    models.FloatField(blank=True, null=True, verbose_name="甲基化水平"),
                ),
                (
                    "cnv_ratio",
                    models.FloatField(blank=True, null=True, verbose_name="CNV比值"),
                ),
                ("annotation", models.TextField(blank=True, verbose_name="注释")),
                (
                    "bam_track_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="BAM Track URL"
                    ),
                ),
                (
                    "bam_index_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="BAM Index URL"
                    ),
                ),
                (
                    "vcf_track_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="VCF Track URL"
                    ),
                ),
                (
                    "vcf_index_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="VCF Index URL"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "变异位点",
                "verbose_name_plural": "变异位点",
                "ordering": ["chromosome", "position"],
            },
        ),
    ]
