# Generated by Django 4.2.30 on 2026-09-02 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_no', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('unknown', '未知')], default='', max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '受检者',
                'verbose_name_plural': '受检者',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('external_source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('product_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('report_type', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('sample_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('tumor_sample_id', models.CharField(blank=True, default='', max_length=128)),
                ('normal_sample_id', models.CharField(blank=True, default='', max_length=128)),
                ('report_date', models.DateField(blank=True, db_index=True, null=True)),
                ('genome_build', models.CharField(blank=True, default='GRCh38', max_length=32)),
                ('status', models.CharField(choices=[('draft', '分析中'), ('review', '待审核'), ('released', '已发布'), ('void', '已作废')], db_index=True, default='draft', max_length=16)),
                ('summary', models.TextField(blank=True, default='')),
                ('conclusion', models.TextField(blank=True, default='')),
                ('patient_snapshot', models.JSONField(blank=True, default=dict)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('annotation_sources', models.JSONField(blank=True, default=dict)),
                ('data_schema_version', models.CharField(default='2.0', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '检测报告',
                'verbose_name_plural': '检测报告',
                'ordering': ['-report_date', '-released_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('pdf', 'PDF'), ('bam', 'BAM'), ('bai', 'BAI'), ('vcf', 'VCF'), ('bed', 'BED'), ('image', 'Image'), ('json', 'JSON'), ('other', 'Other')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('storage_backend', models.CharField(default='local', max_length=32)),
                ('file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('external_url', models.URLField(blank=True, default='', max_length=2048)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='reports.report')),
            ],
            options={
                'verbose_name': '报告附件',
                'verbose_name_plural': '报告附件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '查看'), ('download_pdf', '下载PDF'), ('download_asset', '下载附件')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='reports.report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '报告访问日志',
                'verbose_name_plural': '报告访问日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(db_index=True, max_length=32)),
                ('position', models.BigIntegerField(db_index=True)),
                ('ref', models.CharField(blank=True, default='', max_length=512)),
                ('alt', models.CharField(blank=True, default='', max_length=512)),
                ('gene', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('variant_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('consequence', models.CharField(blank=True, default='', max_length=128)),
                ('allele_frequency', models.FloatField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='reports.report')),
            ],
            options={
                'verbose_name': '报告变异',
                'verbose_name_plural': '报告变异',
                'ordering': ['chromosome', 'position'],
                'indexes': [models.Index(fields=['report', 'gene'], name='reports_rep_report__98207d_idx'), models.Index(fields=['chromosome', 'position'], name='reports_rep_chromos_a6c998_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_source', 'external_id'), name='uniq_report_external_source_external_id'),
        ),
    ]
