# Generated by Django 4.2.30 on 2026-08-10 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_wes_report_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_pdf_file',
            field=models.FileField(blank=True, upload_to='reports/%Y/%m/', verbose_name='正式PDF文件'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_pdf_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='PDF SHA256'),
        ),
        migrations.CreateModel(
            name='ReportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '查看'), ('download_pdf', '下载PDF')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='reports.report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
