# Generated by Django 4.2.30 on 2026-08-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_report_report_pdf_file_report_report_pdf_sha256_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReportSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_no', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='患者编号')),
                ('patient_name', models.CharField(blank=True, max_length=80, verbose_name='患者姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '患者报告台账',
                'verbose_name_plural': '患者报告台账',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(db_index=True, max_length=100, verbose_name='样本编号')),
                ('upload_id', models.CharField(max_length=120, unique=True, verbose_name='上传ID')),
                ('wes_report_id', models.CharField(db_index=True, max_length=100, verbose_name='WES报告ID')),
                ('root_dir', models.CharField(max_length=500, verbose_name='版本目录')),
                ('status', models.CharField(choices=[('active', '当前有效'), ('superseded', '已作废')], db_index=True, default='active', max_length=20)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('payload_sha256', models.CharField(blank=True, max_length=64)),
                ('node_id', models.CharField(blank=True, max_length=100)),
                ('pdf_ready', models.BooleanField(default=False)),
                ('pdf_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='reports.patientreportslot')),
            ],
            options={
                'verbose_name': '样本报告包',
                'verbose_name_plural': '样本报告包',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patientreportslot',
            name='active_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_slots', to='reports.samplebundle'),
        ),
        migrations.AddField(
            model_name='patientreportslot',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_slots', to='reports.report'),
        ),
        migrations.AddField(
            model_name='patientreportslot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BundleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('report_json', '报告JSON'), ('generated_pdf', '生成PDF'), ('generated_html', '生成HTML'), ('qc_plot', '质控图'), ('attachment', '附件'), ('other', '其他')], default='other', max_length=40)),
                ('original_name', models.CharField(max_length=255)),
                ('rel_path', models.CharField(max_length=500)),
                ('abs_path', models.CharField(max_length=1000)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.samplebundle')),
            ],
            options={
                'verbose_name': '报告包文件',
                'verbose_name_plural': '报告包文件',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='samplebundle',
            index=models.Index(fields=['sample_id', 'status'], name='reports_sam_sample__723fb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='bundlefile',
            constraint=models.UniqueConstraint(fields=('bundle', 'rel_path'), name='unique_bundle_file_rel_path'),
        ),
    ]
