"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


DEBUG = env_bool("GAOMEI_WEB_DEBUG", True)
SECRET_KEY = os.environ.get(
    "GAOMEI_WEB_SECRET_KEY",
    "django-insecure-local-development-only",
)
if not DEBUG and SECRET_KEY == "django-insecure-local-development-only":
    raise ImproperlyConfigured("GAOMEI_WEB_SECRET_KEY is required when DEBUG is false")

# Local prototype convenience only. This is automatically disabled whenever
# DEBUG is disabled for a cloud/production deployment.
ALLOW_INSECURE_PASSWORD_RESET = DEBUG

ALLOWED_HOSTS = [
    item.strip() for item in os.environ.get(
        "GAOMEI_WEB_ALLOWED_HOSTS",
        "192.168.3.109,localhost,127.0.0.1",
    ).split(",") if item.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    # Local
    "accounts",
    "reports",
    "ingest",
    "blog",
    "bioblog",
    "company",
    "wes_report",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Production releases symlink backend/db.sqlite3 -> shared/db.sqlite3.
# Workspace must use the independent test copy (shared/db.test.sqlite3) unless
# GAOMEI_WEB_ALLOW_PROD_DB=1 is explicitly set.

_PROD_SQLITE = Path("/home/ubuntu/apps/gaomei_web/shared/db.sqlite3")
_db_name = Path(os.environ.get("GAOMEI_WEB_DB_PATH", str(BASE_DIR / "db.sqlite3"))).expanduser()
try:
    _db_resolved = _db_name.resolve()
except FileNotFoundError:
    _db_resolved = _db_name

_under_release = "apps/gaomei_web" in str(BASE_DIR.resolve()).replace("\\", "/")
if (
    _PROD_SQLITE.exists()
    and _db_resolved == _PROD_SQLITE.resolve()
    and not _under_release
    and not env_bool("GAOMEI_WEB_ALLOW_PROD_DB", False)
):
    raise ImproperlyConfigured(
        "Refusing to open production SQLite from the workspace. "
        "Use shared/db.test.sqlite3 (workspace symlink) or set GAOMEI_WEB_ALLOW_PROD_DB=1."
    )

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _db_name,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.environ.get("GAOMEI_WEB_TIME_ZONE", "Asia/Shanghai")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = Path(os.environ.get("GAOMEI_WEB_STATIC_ROOT", BASE_DIR / "staticfiles"))

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.environ.get("GAOMEI_WEB_MEDIA_ROOT", BASE_DIR / "media"))

# CORS
CORS_ALLOWED_ORIGINS = [
    item for item in os.environ.get(
        "GAOMEI_WEB_CORS_ORIGINS",
        "http://127.0.0.1:18080,http://localhost:18080",
    ).split(",") if item
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    item for item in os.environ.get(
        "GAOMEI_WEB_CSRF_TRUSTED_ORIGINS",
        "http://127.0.0.1:18080,http://localhost:18080",
    ).split(",") if item
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = env_bool("GAOMEI_WEB_SECURE_COOKIES", False)
CSRF_COOKIE_SECURE = env_bool("GAOMEI_WEB_SECURE_COOKIES", False)

# Formal WES HTML/PDF report packages (node9 upload → cloud render).
WES_BUNDLE_ROOT = Path(os.environ.get("GAOMEI_WES_BUNDLE_ROOT", MEDIA_ROOT / "wes_bundles"))
WES_REPORT_DATA_DIR = Path(os.environ.get("GAOMEI_WES_REPORT_DATA_DIR", MEDIA_ROOT / "wes_reports"))
WES_REPORT_OUTPUT_DIR = Path(os.environ.get("GAOMEI_WES_REPORT_OUTPUT_DIR", MEDIA_ROOT / "wes_output"))
WES_REPORT_EXAMPLE_DIR = Path(
    os.environ.get("GAOMEI_WES_REPORT_EXAMPLE_DIR", BASE_DIR / "wes_report_examples")
)

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# SimpleJWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
