"""Create one rich WES report for local UI and API integration testing."""

import os
from datetime import date

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from django.contrib.auth.models import User
from django.utils import timezone

from reports.models import Report, ReportItem


user, created = User.objects.get_or_create(
    username="zhangsan",
    defaults={"email": "zhangsan@example.com"},
)
if created:
    user.set_password("test123456")
    user.save()

analysis_data = {
    "is_demo": True,
    "pipeline_version": "gaomei-wes v1.0",
    "analysis_date": "2026-07-29",
    "assay": "肿瘤-正常配对全外显子组测序",
    "qc": {
        "status": "PASS",
        "tumor_mean_depth": 146.8,
        "normal_mean_depth": 118.4,
        "tumor_mapping_rate": 99.42,
        "normal_mapping_rate": 99.61,
        "tumor_duplication_rate": 18.7,
        "normal_duplication_rate": 15.2,
        "target_20x": 97.8,
        "target_100x": 72.4,
    },
    "biomarkers": {
        "tmb": 3.2,
        "tmb_unit": "mut/Mb",
        "tmb_class": "TMB-L",
        "tmb_variant_count": 66,
        "msi_score": 1.3,
        "msi_status": "MSS",
        "tumor_purity": 0.42,
        "hla_class_i": [
            "HLA-A*31:01",
            "HLA-A*33:03",
            "HLA-B*15:01",
            "HLA-B*58:01",
            "HLA-C*03:02",
            "HLA-C*15:02",
        ],
    },
    "counts": {
        "raw_mutect2": 642,
        "mutect2_pass": 168,
        "manual_filter_pass": 66,
        "reportable": 6,
        "snv": 5,
        "indel": 1,
    },
    "consequence_counts": {
        "错义突变": 4,
        "移码突变": 1,
        "无义突变": 1,
    },
    "coverage_by_chromosome": [
        {"chromosome": "chr1", "depth": 149.2, "coverage20x": 98.4},
        {"chromosome": "chr7", "depth": 151.8, "coverage20x": 98.1},
        {"chromosome": "chr17", "depth": 158.6, "coverage20x": 98.9},
        {"chromosome": "chr18", "depth": 142.4, "coverage20x": 97.6},
        {"chromosome": "chrX", "depth": 91.7, "coverage20x": 94.2},
    ],
    "filter_thresholds": {
        "TLOD": ">= 6.3",
        "Tumor DP": ">= 20",
        "Tumor ALT reads": ">= 5",
        "Tumor AF": ">= 2%",
        "Normal DP": ">= 20",
        "Normal ALT reads": "<= 2",
        "Normal AF": "<= 2%",
        "Population max AF": "<= 0.1% or missing",
    },
    "cnv": [
        {"gene": "ERBB2", "type": "gain", "log2": 0.74, "copy_number": 4, "status": "候选扩增"},
        {"gene": "CDKN2A", "type": "loss", "log2": -0.61, "copy_number": 1, "status": "候选缺失"},
    ],
    "msi_loci": [
        {"locus": "BAT-25", "score": 0.8, "status": "稳定"},
        {"locus": "BAT-26", "score": 1.1, "status": "稳定"},
        {"locus": "NR-24", "score": 0.6, "status": "稳定"},
    ],
    "hla_typing": [
        {"locus": "HLA-A", "allele1": "A*31:01:02G", "allele2": "A*33:03:01G", "resolution": "6位/G-group"},
        {"locus": "HLA-B", "allele1": "B*15:01:01G", "allele2": "B*58:01:01G", "resolution": "6位/G-group"},
        {"locus": "HLA-C", "allele1": "C*03:02:01G", "allele2": "C*15:02:01G", "resolution": "6位/G-group"},
    ],
    "organ_risks": [
        {"key": "liver", "name": "肝脏", "score": 8.7, "genes": ["TP53", "CTNNB1"], "evidence": "演示数据", "recommendation": "界面验证数据，不代表患者真实器官风险。"},
        {"key": "prostate", "name": "前列腺", "score": 7.6, "genes": ["AR", "PTEN"], "evidence": "演示数据", "recommendation": "界面验证数据，不代表患者真实器官风险。"},
        {"key": "pancreas", "name": "胰腺", "score": 6.8, "genes": ["KRAS", "SMAD4"], "evidence": "演示数据", "recommendation": "界面验证数据，不代表患者真实器官风险。"},
        {"key": "colon", "name": "结直肠", "score": 5.4, "genes": ["APC", "PIK3CA"], "evidence": "演示数据", "recommendation": "界面验证数据，不代表患者真实器官风险。"},
        {"key": "bladder", "name": "膀胱", "score": 4.3, "genes": ["FGFR3", "TERT"], "evidence": "演示数据", "recommendation": "界面验证数据，不代表患者真实器官风险。"},
        {"key": "gallbladder", "name": "胆囊", "score": 3.4, "genes": ["ERBB2"], "evidence": "演示数据", "recommendation": "界面验证数据，不代表患者真实器官风险。"},
        {"key": "kidney", "name": "肾脏", "score": 2.2, "genes": ["VHL"], "evidence": "演示数据", "recommendation": "界面验证数据，不代表患者真实器官风险。"},
        {"key": "trachea", "name": "气管", "score": 1.6, "genes": [], "evidence": "演示数据", "recommendation": "界面验证数据，不代表患者真实器官风险。"},
    ],
    "contamination": {
        "fraction": 0.007,
        "tumor_purity": 0.42,
        "orientation_bias_status": "PASS",
        "pair_concordance": "MATCH",
    },
    "workflow_steps": [
        {"step": "01", "label": "FASTQ QC", "status": "completed"},
        {"step": "02", "label": "Alignment", "status": "completed"},
        {"step": "03", "label": "BQSR", "status": "completed"},
        {"step": "04", "label": "Mutect2", "status": "completed"},
        {"step": "05", "label": "Annotation", "status": "completed"},
        {"step": "06", "label": "Report", "status": "completed"},
    ],
}

annotation_sources = [
    {"name": "Ensembl VEP", "version": "115", "assembly": "GRCh38", "purpose": "转录本、后果、HGVS", "status": "已完成"},
    {"name": "ANNOVAR refGeneWithVer", "version": "2025-03", "assembly": "hg38", "purpose": "RefSeq基因注释", "status": "已完成"},
    {"name": "dbSNP", "version": "avsnp151", "assembly": "hg38", "purpose": "rs编号", "status": "已完成"},
    {"name": "ClinVar", "version": "2026-07快照", "assembly": "GRCh38", "purpose": "临床意义", "status": "已完成"},
    {"name": "gnomAD exomes", "version": "4.1.1", "assembly": "GRCh38", "purpose": "群体频率", "status": "已完成"},
    {"name": "dbNSFP", "version": "4.7c", "assembly": "GRCh38", "purpose": "多算法致病性预测", "status": "下载中/待接入"},
    {"name": "CIViC", "version": "2026-07快照", "assembly": "GRCh38", "purpose": "肿瘤临床证据", "status": "研发审核"},
    {"name": "OncoKB", "version": "API接口预留", "assembly": "GRCh38", "purpose": "药物与证据等级", "status": "未启用"},
]

report, _ = Report.objects.update_or_create(
    user=user,
    sample_id="SH05677",
    report_type="mutation",
    defaults={
        "title": "SH05677 肿瘤-正常配对WES综合报告（演示）",
        "report_date": date(2026, 7, 29),
        "summary": "完成肿瘤与配对正常样本WES分析。最终报告位点经过Mutect2、VEP/ANNOVAR多库注释、硬阈值过滤和人工审核。",
        "conclusion": "本页面为系统联调演示。治疗相关信息仅展示知识库整合能力，正式结论必须经过分析员与审核员确认。",
        "report_number": "GM-WES-20260729-001",
        "status": "released",
        "genome_build": "GRCh38",
        "tumor_sample_id": "SH05677",
        "normal_sample_id": "SH05678",
        "patient_info": {
            "name": "张三（演示）",
            "sex": "男",
            "age": 58,
            "clinical_diagnosis": "实体瘤送检样本（演示）",
            "specimen": "肿瘤组织 / 外周血",
            "institution": "高美基因演示中心",
        },
        "analysis_data": analysis_data,
        "annotation_sources": annotation_sources,
        "reviewed_by": "系统演示审核员",
        "released_at": timezone.now(),
    },
)

report.items.all().delete()

items = [
    {
        "gene": "NEDD4L",
        "chromosome": "18",
        "position": 58335478,
        "ref_allele": "C",
        "alt_allele": "T",
        "variant_type": "SNP",
        "significance": "vus",
        "af": 0.041,
        "annotation": "低频错义突变，证据需结合原始测序和知识库复核。",
        "transcript": "ENST00000400345",
        "hgvs_c": "c.1066C>T",
        "hgvs_p": "p.Pro356Ser",
        "consequence": "missense_variant",
        "tumor_depth": 248,
        "tumor_alt_reads": 10,
        "normal_depth": 99,
        "normal_alt_reads": 0,
        "tlod": 13.91,
        "filter_status": "PASS; manual_filter_pass",
        "review_status": "reviewed",
        "annotations": {
            "VEP_SYMBOL": "NEDD4L",
            "ANNOVAR_Function": "exonic",
            "ClinVar": "未收录",
            "gnomAD_AF": 0.00008,
            "dbNSFP_REVEL": 0.42,
            "dbNSFP_SIFT": "D",
            "dbNSFP_PolyPhen2": "P",
            "dbSNP": "rs示例",
        },
        "therapies": [],
        "neoantigens": [
            {
                "peptide": "VLAPNPSRL",
                "length": 9,
                "hla": "HLA-A*31:01",
                "netmhcpan_rank": 0.31,
                "netmhcpan_affinity": 41.2,
                "mhcflurry_affinity": 63.8,
                "consensus": "both_strong",
            },
            {
                "peptide": "KVLAPNPSRL",
                "length": 10,
                "hla": "HLA-B*15:01",
                "netmhcpan_rank": 1.4,
                "netmhcpan_affinity": 284.1,
                "mhcflurry_affinity": 331.0,
                "consensus": "weak_supported",
            },
        ],
    },
    {
        "gene": "TP53",
        "chromosome": "17",
        "position": 7674220,
        "ref_allele": "C",
        "alt_allele": "T",
        "variant_type": "SNP",
        "significance": "pathogenic",
        "af": 0.286,
        "annotation": "TP53热点错义变异，需结合癌种和临床证据判读。",
        "transcript": "NM_000546.6",
        "hgvs_c": "c.743G>A",
        "hgvs_p": "p.Arg248Gln",
        "consequence": "missense_variant",
        "tumor_depth": 164,
        "tumor_alt_reads": 47,
        "normal_depth": 121,
        "normal_alt_reads": 0,
        "tlod": 42.7,
        "filter_status": "PASS; manual_filter_pass",
        "review_status": "reviewed",
        "annotations": {
            "VEP_SYMBOL": "TP53",
            "ANNOVAR_Function": "exonic",
            "ClinVar": "Pathogenic",
            "gnomAD_AF": 0.00001,
            "dbNSFP_REVEL": 0.96,
            "dbNSFP_SIFT": "D",
            "dbNSFP_PolyPhen2": "D",
            "dbSNP": "rs11540652",
        },
        "therapies": [
            {
                "drug": "临床试验匹配",
                "response": "研究证据",
                "level": "CIViC E",
                "disease": "实体瘤",
                "source": "CIViC",
                "status": "需审核",
            }
        ],
        "neoantigens": [
            {
                "peptide": "SSCMGGMNR",
                "length": 9,
                "hla": "HLA-A*33:03",
                "netmhcpan_rank": 0.44,
                "netmhcpan_affinity": 48.9,
                "mhcflurry_affinity": 82.6,
                "consensus": "netmhcpan_only_strong",
            }
        ],
    },
    {
        "gene": "PIK3CA",
        "chromosome": "3",
        "position": 179218303,
        "ref_allele": "G",
        "alt_allele": "A",
        "variant_type": "SNP",
        "significance": "likely_pathogenic",
        "af": 0.182,
        "annotation": "PIK3CA激活性热点候选，药物提示需按癌种审核。",
        "transcript": "NM_006218.4",
        "hgvs_c": "c.1633G>A",
        "hgvs_p": "p.Glu545Lys",
        "consequence": "missense_variant",
        "tumor_depth": 198,
        "tumor_alt_reads": 36,
        "normal_depth": 133,
        "normal_alt_reads": 0,
        "tlod": 31.4,
        "filter_status": "PASS; manual_filter_pass",
        "review_status": "reviewed",
        "annotations": {
            "ClinVar": "Likely pathogenic",
            "gnomAD_AF": 0.00002,
            "dbNSFP_REVEL": 0.91,
            "dbNSFP_SIFT": "D",
            "dbSNP": "rs104886003",
        },
        "therapies": [
            {
                "drug": "PI3K通路抑制剂",
                "response": "潜在敏感",
                "level": "知识库提示",
                "disease": "特定癌种",
                "source": "CIViC",
                "status": "需癌种审核",
            }
        ],
        "neoantigens": [],
    },
    {
        "gene": "ARID1A",
        "chromosome": "1",
        "position": 27023220,
        "ref_allele": "A",
        "alt_allele": "AT",
        "variant_type": "InDel",
        "significance": "likely_pathogenic",
        "af": 0.124,
        "annotation": "移码变异，预计导致蛋白截短。",
        "transcript": "NM_006015.6",
        "hgvs_c": "c.3121dup",
        "hgvs_p": "p.Asn1041LysfsTer18",
        "consequence": "frameshift_variant",
        "tumor_depth": 137,
        "tumor_alt_reads": 17,
        "normal_depth": 102,
        "normal_alt_reads": 0,
        "tlod": 18.6,
        "filter_status": "PASS; manual_filter_pass",
        "review_status": "reviewed",
        "annotations": {
            "ClinVar": "未收录",
            "gnomAD_AF": 0,
            "dbNSFP_REVEL": None,
            "dbSNP": "未收录",
        },
        "therapies": [],
        "neoantigens": [],
    },
    {
        "gene": "ERBB2",
        "chromosome": "17",
        "position": 39723970,
        "ref_allele": "G",
        "alt_allele": "A",
        "variant_type": "SNP",
        "significance": "vus",
        "af": 0.067,
        "annotation": "ERBB2错义变异；同时存在拷贝数增益候选。",
        "transcript": "NM_004448.4",
        "hgvs_c": "c.929G>A",
        "hgvs_p": "p.Ser310Phe",
        "consequence": "missense_variant",
        "tumor_depth": 224,
        "tumor_alt_reads": 15,
        "normal_depth": 146,
        "normal_alt_reads": 0,
        "tlod": 16.8,
        "filter_status": "PASS; manual_filter_pass",
        "review_status": "pending",
        "annotations": {
            "ClinVar": "Uncertain significance",
            "gnomAD_AF": 0.00004,
            "dbNSFP_REVEL": 0.78,
            "dbNSFP_SIFT": "D",
            "dbSNP": "rs示例",
        },
        "therapies": [],
        "neoantigens": [],
    },
    {
        "gene": "KMT2D",
        "chromosome": "12",
        "position": 49018918,
        "ref_allele": "C",
        "alt_allele": "A",
        "variant_type": "SNP",
        "significance": "likely_pathogenic",
        "af": 0.093,
        "annotation": "无义变异，预计导致蛋白提前终止。",
        "transcript": "NM_003482.4",
        "hgvs_c": "c.13825C>A",
        "hgvs_p": "p.Ser4609Ter",
        "consequence": "stop_gained",
        "tumor_depth": 151,
        "tumor_alt_reads": 14,
        "normal_depth": 118,
        "normal_alt_reads": 0,
        "tlod": 15.2,
        "filter_status": "PASS; manual_filter_pass",
        "review_status": "reviewed",
        "annotations": {
            "ClinVar": "未收录",
            "gnomAD_AF": 0,
            "dbNSFP_REVEL": 0.88,
            "dbSNP": "未收录",
        },
        "therapies": [],
        "neoantigens": [],
    },
]

for item in items:
    ReportItem.objects.create(report=report, **item)

print(f"Rich WES demo report ready: id={report.id}, items={report.items.count()}")
print("Login: zhangsan / test123456")
