# Generated by Django 4.2.30 on 2026-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="公司名称")),
                (
                    "slogan",
                    models.CharField(blank=True, max_length=300, verbose_name="标语"),
                ),
                ("description", models.TextField(verbose_name="公司介绍")),
                ("mission", models.TextField(blank=True, verbose_name="使命")),
                ("vision", models.TextField(blank=True, verbose_name="愿景")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="电话"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=300, verbose_name="地址"),
                ),
                (
                    "wechat",
                    models.CharField(blank=True, max_length=100, verbose_name="微信公众号"),
                ),
                (
                    "founded_year",
                    models.IntegerField(blank=True, null=True, verbose_name="成立年份"),
                ),
            ],
            options={
                "verbose_name": "公司信息",
                "verbose_name_plural": "公司信息",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="服务名称")),
                ("description", models.TextField(verbose_name="服务描述")),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-flask",
                        max_length=50,
                        verbose_name="图标(Font Awesome)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否展示")),
            ],
            options={
                "verbose_name": "服务项目",
                "verbose_name_plural": "服务项目",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("position", models.CharField(max_length=100, verbose_name="职位")),
                ("bio", models.TextField(blank=True, verbose_name="简介")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="team/", verbose_name="照片"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "团队成员",
                "verbose_name_plural": "团队成员",
                "ordering": ["order", "name"],
            },
        ),
    ]
