# Generated by Django 4.2.30 on 2026-09-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_teammember_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('phone', models.CharField(max_length=40, verbose_name='联系电话')),
                ('category', models.CharField(choices=[('research', '科研合作'), ('product', '检测产品'), ('deploy', '私有化部署'), ('career', '加入我们'), ('other', '其他留言')], default='product', max_length=20, verbose_name='咨询类型')),
                ('product', models.CharField(blank=True, max_length=120, verbose_name='产品方向')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('status', models.CharField(choices=[('new', '未读'), ('read', '已读'), ('done', '已处理')], default='new', max_length=10, verbose_name='状态')),
                ('admin_note', models.CharField(blank=True, max_length=300, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '官网留言',
                'verbose_name_plural': '官网留言',
                'ordering': ['-created_at'],
            },
        ),
    ]
