# Generated by Django 4.2.30 on 2026-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('research', '科研合作'), ('product', '检测产品'), ('interpret', '产品解读'), ('deploy', '私有化部署'), ('career', '加入我们'), ('other', '其他留言')], default='product', max_length=20, verbose_name='咨询类型'),
        ),
    ]
