# Generated by Django 4.2.30 on 2026-06-30 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("slug", models.SlugField(unique=True, verbose_name="URL标识")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名称")),
                ("slug", models.SlugField(unique=True, verbose_name="URL标识")),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL标识"),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "summary",
                    models.TextField(blank=True, max_length=500, verbose_name="摘要"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/", verbose_name="封面图片"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="浏览量")),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="blog.tag", verbose_name="标签"
                    ),
                ),
            ],
            options={
                "verbose_name": "博客文章",
                "verbose_name_plural": "博客文章",
                "ordering": ["-published_at"],
            },
        ),
    ]
