# Generated by Django 4.2.30 on 2026-07-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="wechat_link",
            field=models.URLField(
                blank=True,
                help_text="微信公众号文章链接",
                max_length=500,
                null=True,
                verbose_name="微信链接",
            ),
        ),
    ]
