# Generated by Django 4.2.30 on 2026-07-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_wechat_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, default="", verbose_name="内容"),
        ),
    ]
