# Generated by Django 4.2.30 on 2026-07-03 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BioCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("slug", models.SlugField(unique=True, verbose_name="URL标识")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="fas fa-flask",
                        max_length=50,
                        verbose_name="图标类名",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="#667eea", max_length=20, verbose_name="主题色"
                    ),
                ),
            ],
            options={
                "verbose_name": "生信分类",
                "verbose_name_plural": "生信分类",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BioTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名称")),
                ("slug", models.SlugField(unique=True, verbose_name="URL标识")),
            ],
            options={
                "verbose_name": "生信标签",
                "verbose_name_plural": "生信标签",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BioPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL标识"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="使用 $$...$$ 或 $...$ 包裹 LaTeX 公式",
                        verbose_name="内容 (支持LaTeX)",
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, max_length=500, verbose_name="摘要"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="bioblog/", verbose_name="封面图片"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="浏览量")),
                ("is_pinned", models.BooleanField(default=False, verbose_name="置顶")),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bioblog.biocategory",
                        verbose_name="分类",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="bioblog.biotag", verbose_name="标签"
                    ),
                ),
            ],
            options={
                "verbose_name": "生信文章",
                "verbose_name_plural": "生信文章",
                "ordering": ["-is_pinned", "-published_at"],
            },
        ),
    ]
