from django.urls import path
from .views_v1 import (
    MePatientView,
    MeReportListView,
    ReportAccessSummaryView,
    ReportAssetDownloadView,
    ReportAssetListView,
    ReportDetailView,
    ReportReleaseView,
    ReportSubmitReviewView,
    ReportVoidView,
    ReportVariantListView,
)
from .db_browser_views import (
    AccessLogDbView,
    ApiKeyDbView,
    AssetDbDetailView,
    AssetDbView,
    DbBrowserCatalogView,
    IngestEventDbView,
    PatientDbDetailView,
    PatientDbView,
    ReportDbDetailView,
    ReportDbView,
    VariantDbView,
)

urlpatterns = [
    path("me/patient/", MePatientView.as_view(), name="v1_me_patient"),
    path("me/reports/", MeReportListView.as_view(), name="v1_me_reports"),
    path("reports/access-summary/", ReportAccessSummaryView.as_view(), name="v1_report_access_summary"),
    path("reports/<int:pk>/", ReportDetailView.as_view(), name="v1_report_detail"),
    path("reports/<int:pk>/release/", ReportReleaseView.as_view(), name="v1_report_release"),
    path("reports/<int:pk>/submit-review/", ReportSubmitReviewView.as_view(), name="v1_report_submit_review"),
    path("reports/<int:pk>/void/", ReportVoidView.as_view(), name="v1_report_void"),
    path("reports/<int:pk>/variants/", ReportVariantListView.as_view(), name="v1_report_variants"),
    path("reports/<int:pk>/assets/", ReportAssetListView.as_view(), name="v1_report_assets"),
    path(
        "reports/<int:pk>/assets/<int:asset_id>/download/",
        ReportAssetDownloadView.as_view(),
        name="v1_report_asset_download",
    ),
    path("db-browser/", DbBrowserCatalogView.as_view(), name="db_browser_catalog"),
    path("db-browser/patients/", PatientDbView.as_view(), name="db_browser_patients"),
    path("db-browser/patients/<int:pk>/", PatientDbDetailView.as_view(), name="db_browser_patient_detail"),
    path("db-browser/reports/", ReportDbView.as_view(), name="db_browser_reports"),
    path("db-browser/reports/<int:pk>/", ReportDbDetailView.as_view(), name="db_browser_report_detail"),
    path("db-browser/assets/", AssetDbView.as_view(), name="db_browser_assets"),
    path("db-browser/assets/<int:pk>/", AssetDbDetailView.as_view(), name="db_browser_asset_detail"),
    path("db-browser/variants/", VariantDbView.as_view(), name="db_browser_variants"),
    path("db-browser/access-logs/", AccessLogDbView.as_view(), name="db_browser_access_logs"),
    path("db-browser/ingest-events/", IngestEventDbView.as_view(), name="db_browser_ingest_events"),
    path("db-browser/api-keys/", ApiKeyDbView.as_view(), name="db_browser_api_keys"),
]
